### ISSUE TITLE
Gateway timeouts when computing codelist definitions

### ISSUE THREAD

**Issue by inglesp** [opensafely/opencodelists#101]
Codelist definitions are computed on the fly, but this is slow for large SNOMED CT codelists, and can lead to gateway timeouts.

One solution might be to turn on caching, in Cloudflare or elsewhere.

Another solution might be to precompute definitions when a codelist CSV is uploaded.  For now, the definition can be stored as JSON in the database.  As it is only internal users who upload CSVs, we wouldn't need to add a job queue to handle this.

**Comment by ghickman** [comment]
> As it is only internal users who upload CSVs

Was your thinking here that the flow would be something like:
1. Create codelist/update version/create version
1. Run managment command to generate definitions [via edmbot maybe?]

?

**Comment by inglesp** [comment]
That would work -- or we could just risk letting the gateway time out.

**Comment by ghickman** [comment]
Ok, lets try that first and see how many timeouts we get with internal usage.  I'll focus on the upfront generation first.

**Comment by ghickman** [comment]
[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1836017882/)

**Comment by ghickman** [comment]
All URLs linked to the Sentry issue (linked above) resolved with their definition tabs enabled.  I've resolved the Sentry issue so we get a notification if it happens again.
