### ISSUE TITLE
Investigate Snomed Cancer Codelist Size

### ISSUE THREAD

**Issue by ghickman** [opensafely/opencodelists#117]
The SNOMED codelist `cancer-excluding-lung-and-haematological-snomed` is huge.  It includes the code for `Clinical finding`, an ancestor for a large chunk of SNOMED, this seems spurious.

We need to work out why our CTV3 mapping code thinks `Clinical finding` should be included.

**Comment by ghickman** [comment]
The CTV3 Concept [`A7886`](https://codelists.opensafely.org/ctv3/concept/A7886/) produces the `Clinical finding` SNOMED concept.

**Comment by ghickman** [comment]
Our mapper lists these CTV3 concepts as related to the `Clinical finding` SNOMED concept:

| Code  | Name |
| ----- | ---- |
| R.... | [D]Symptoms, signs and ill-defined conditions |
| R04z. | [D]Other symptoms or [D]lesion |
| R12.. | [D]Nonspecific findings in other body substances |
| Ryu7. | [X]General symptoms and signs |
| Ryu79 | [X]Other specified general symptoms and signs |
| Rz... | [D]Symptoms, signs and ill-defined conditions NOS |
| U.... | [X]External causes of morbidity and mortality |
| U8... | [X]Supplementary factors related to causes of morbidity and mortality classified elsewhere |
| X75Px | Finding |
| XM06O | Clinical observation: symptoms and signs |
| XaBVJ | Clinical findings |
| ZV4y. | [V]Person with other specified health problems |
| ZV4z. | [V]Unspecified health problems |
| ZV6.. | [V]Other reasons for encounter |
| ZV6y. | [V]Other reasons for encounter OS |
| ZV6z. | [V]Other reasons for encounter NOS |
| ZVu58 | [X]Persons encountering health services in other specified circumstances |
| ZVy.. | [V]Other specified reasons for encounter |
| ZVz.. | [V]Unspecified reasons for encounter |

**Comment by ghickman** [comment]
`X75Px | Finding` looks like a likely candidate for why we're getting `Clinical finding`, it's only a couple of levels from the top of the CTV3 hierarchy.

**Comment by ghickman** [comment]
Given CTV3 concept `A7886` we start with two initial SNOMED concepts:

* `3290189011` | Malignant neoplastic disease co-occurrent with human immunodeficiency virus infection [(disorder)]
* `363346000` | Malignant tumour/neoplastic disease OR Cancer (roughly, becuase there are 6 terms)

**Comment by ghickman** [comment]
# Recap

We have a SNOMED Codelist (`cancer-excluding-lung-and-haematological-snomed`) which is pulling in a lot of concepts because of the concept Clinical finding (`404684003`).

This Codelist was generated from a CTV3 Codelist.

We've found that the Concept `Human immunodeficiency virus with secondary cancers` (`A7886`) is the CTV3 concept which ends up producing `Clinical finding` in the SNOMED Codelist.

We've mirrored the [`ctv3_to_snomedct`](https://github.com/opensafely/opencodelists/blob/master/mappings/ctv3sctmap2/mappers.py#L11-L106) mapper flow to generate edges based on how we found the SNOMED codes, then used networkx to find paths from the initial CTV3 concept, `A7886`, to the spurious SNOMED concept, `404684003` (`Clinical finding`).

This produced 24 paths, arrayed like so:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/OAuq6Rvw/clinical-finding.svg?v=d8e5a5cb77937c243e0600f2da50ec9f)

There's a cyclical path down near `Clinical finding` which we thinking might be a cause:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/nOukRWnB/Image%202020-08-26%20at%2010.26.34%20am.png?v=3c2105a4d7324941a2864329a9ba6300)

#### 1 `443679004` -> `396611000000109`
_from query table_
* Source: `Malignant neoplasm of skeletal system (disorder)` (`443679004`)
* Destination: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage (disorder)` (`396611000000109`)

#### 2 `396611000000109` -> `443679004`
_from history sub_
* Source: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage (disorder)` (`396611000000109`)
* Destination: `Malignant neoplasm of skeletal system (disorder)` (`443679004`)

#### 3 `443679004` -> `462251000000102`
_from query table_
* Source: `Malignant neoplasm of skeletal system (disorder)` (`443679004`)
* Destination: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage of limbs (disorder)` (`462251000000102`)

#### 4`462251000000102` -> `443679004`
_from history sub_
* Source: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage of limbs (disorder)` (`462251000000102`)
* Destination: `Malignant neoplasm of skeletal system (disorder)` (`443679004`)

#### 5 `363346000` -> `396611000000109`
_from query table_
* Source: `Malignant neoplastic disease (disorder)` (`363346000`)
* Destination: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage (disorder)` (`396611000000109`)

#### 6 `363346000` -> `462251000000102`
_from query table_
* Source: `Malignant neoplastic disease (disorder)` (`363346000`)
* Destination: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage of limbs (disorder)` (`462251000000102`)

#### 7 `396611000000109` -> `404684003`
_from history sub_
* Source: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage (disorder)` (`396611000000109`)
* Destination: `Clinical finding (finding)` (`404684003`)

#### 8 `462251000000102` -> `404684003`
_from history sub_
* Source: `[X]Malignant neoplasm of overlapping lesion of bone and articular cartilage of limbs (disorder)` (`462251000000102`)
* Destination: `Clinical finding (finding)` (`404684003`)

**Comment by ghickman** [comment]
Looking at other edges in the zoomed out graph, the initial one is very odd.  The root node from CTV3 (`Human immunodeficiency virus with secondary cancers`, `A7886`) gives us a far less specific Concept in SNOMED (`Malignant neoplastic disease (disorder)`, `363346000`).

**Comment by ghickman** [comment]
Looking in the NHSD mapping file I've found 7 occurrences of `A7886` (lines 212169 - 212175) with 4 of those pointing to the relevant SNOMED concept (`363346000`):

| CTV3 Concept ID | CTV3 Term ID | CTV3 Term Type | SNOMED Concept ID | SNOMED Description ID | Map Status | Effective Date | Is Assured |
|-----|-----|-----|-----|-----|-----|-----|-----|
| `A7886` | `Y71g3` | `P` | `363346000` | `1208875016` | ❌ | `2017-03-28` | ✅ 
| `A7886` | `Y71g3` | `P` | `363346000` | `1208875016` | ✅ | `2016-03-23` | ✅
| `A7886` | `Y71g3` | `P` | `363346000` | `1208875016` | ❌ | `2018-06-07` | ❌ 
| `A7886` | `Y71g3` | `P` | `363346000` | `1208875016` | ✅ | `2017-03-28` | ❌

**Comment by ghickman** [comment]
We've tracked it down to a combination of two things:
* We ignore Map Status = False records when importing mappings
* A misunderstanding around what effective date codifies.

The four relevant fields for "should we use this mapping" are:

#### Map ID
A unique identifier, implemented with UUID.

#### Map Status
The status of a mapping:
* `0`: Inactive
* `1`: Active
* `2`: Ambiguous with a SNOMED CT target concept marked as ambiguous.
* `3`: Ambiguous with no ambiguous SNOMED CT target concept.


#### Effective Date
On what date a mapping came into effect.

This also shows when a mapping overrides a previous version, based on Map ID.


#### Is Assured
A boolean showing if the mapping been clinically assured.


---

Currently we look for mappings which are both active and assured.
This is correct but returns the wrong data because we ignored inactive mappings on import.

In the case of `A7886` -> `363346000` we have two pairs of records based on ID:

| Map ID | CTV3 Concept ID | SNOMED ID | Map Status | Effective Date | Is Assured? |
|-----|-----|-----|-----|-----|-----|
| `b939a53e-f13e-11e5-a545-b8ca3ac18f3c` | `A7886` | `363346000` | ❌ | `2017-03-28` | ✅ |
| `b939a53e-f13e-11e5-a545-b8ca3ac18f3c` | `A7886` | `363346000` | ✅ | `2016-03-23` | ✅ |
| `001cb77f-13b3-11e7-a3e9-b8ca3ac18f3c` | `A7886` | `363346000` | ❌ | `2018-06-07` | ❌ |
| `001cb77f-13b3-11e7-a3e9-b8ca3ac18f3c` | `A7886` | `363346000` | ✅ | `2017-03-28` | ❌ |

The latest date in both pairs sets the map status to Inactive, which is what we should be capturing in our imported data.
Then we'll no longer select this mapping when looking for SNOMED Concepts mapped to `A7886`.

**Comment by inglesp** [comment]
I think we've got to the bottom of this, in a combination of this issue and #163.
