### ISSUE TITLE
Where are the Sentry notifications?

### ISSUE THREAD

**Issue by inglesp** [opensafely/opencodelists#131]
@evansd set up Sentry in 36ef6bdab8150c0dd480c61f960bf5ef06081ef5, but I've never had any notifications.

**Comment by evansd** [comment]
Sentry doesn't notify by default, we have to set up alerting rules. I've created a basic rule which sends us a notification for all errors (subject to not re-notifying about the same issue within 30 minutes). Given that we're not expecting a great deal of public traffic this oughtn't to be too noisy but we can always make the rules more sophisticated if we need to.

@inglesp Can you close this whenever the first notification comes through? (I'd test it it now but I don't know the best way of deliberately triggering an error in opencodelists)

**Comment by evansd** [comment]
Just seen a notification come through
