### ISSUE TITLE
Bug: Blank page being caused when changing a code status

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/opencodelists#156]
I just tried to change a code status from `excluded` to no selection. The page went blank. It doesn't appear to happen with every code. The code from devloper tools in chrome is below

`Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at getDescendants (<anonymous>:599:53)
    at getDescendants (<anonymous>:608:33)
    at getDescendants (<anonymous>:608:33)
    at <anonymous>:719:13
    at Array.filter (<anonymous>)
    at codeStatus (<anonymous>:718:76)
    at updateCodeToStatus (<anonymous>:663:43)
    at CodelistBuilder.<anonymous> (<anonymous>:49:23)
    at getStateFromUpdate (react-dom.development.js:12428)
    at processUpdateQueue (react-dom.development.js:12559)`

**Comment by brianmackenna** [comment]
This specific bug arose on https://codelists.opensafely.org/builder/brian-mackenna/diabetic-ketoacidosis/search/dka/
when amending the `DKA` term search in the specific code `Ketoacidosis in type II diabetes mellitus (421750000)` I have copied the code below from the failed page which may or may not be useful!

```
builder.bundle.js:22 TypeError: this.childMap[e] is not iterable
    at Object.getDescendants (builder.bundle.js:30)
    at Object.getDescendants (builder.bundle.js:30)
    at builder.bundle.js:30
    at Array.filter (<anonymous>)
    at Object.codeStatus (builder.bundle.js:30)
    at Object.updateCodeToStatus (builder.bundle.js:30)
    at i.<anonymous> (builder.bundle.js:30)
    at sa (builder.bundle.js:22)
    at Fi (builder.bundle.js:22)
    at go (builder.bundle.js:22)
Zi @ builder.bundle.js:22
builder.bundle.js:22 Uncaught TypeError: this.childMap[e] is not iterable
    at Object.getDescendants (builder.bundle.js:30)
    at Object.getDescendants (builder.bundle.js:30)
    at builder.bundle.js:30
    at Array.filter (<anonymous>)
    at Object.codeStatus (builder.bundle.js:30)
    at Object.updateCodeToStatus (builder.bundle.js:30)
    at i.<anonymous> (builder.bundle.js:30)
    at sa (builder.bundle.js:22)
    at Fi (builder.bundle.js:22)
    at go (builder.bundle.js:22)
```

**Comment by ghickman** [comment]
Testing locally:
* Pull a copy of the prod db
* Take ownership of Brian's codelist (so you can edit it) by editing the db with `update builder_draftcodelist set owner_id = '<your user>' where id = 9;`

The bug can be triggered by clicking any already-selected state, eg the concept `Ketoacidosis in type II diabetes mellitus (421750000)` is excluded so clicking exclude again triggers the bug.

Following `421750000` for simplicity…

The click handler, `CodelistBuilder.updateStatus()` (passed down through `<Table>` to `<Button>`) builds up a list of updates by calling `Hierarchy.updateCodeToStatus()`, which in turn makes a call to `Hierarchy.codeStatus()` for each of the given code's descendants.  Inside this loop (and its calls to `codeStatus()`) is where we start finding the code `55571001` which is the code that triggers the exception.

Next step is to investigate how the creation of `significantIncludedOrExcludedAncestors` in `codeStatus()` triggers the exception in `getDescendants()`.

The childMap both in the backend and frontend look the same, at least in that neither has a key for `55571001`.

**Comment by ghickman** [comment]
I took a bit of detour into trying to work out why the updater function we call in `CodelistBuilder.updateStatus()` was being fired twice.  It seems very related to [this React ticket](https://github.com/facebook/react/issues/12856) but we're not using `ReactStrict` or flipping webpack to `production` mode didn't change that.  And it turned out to not fix the issue.

In a classic case of "was it really that simple", this fix makes the page appear to work as intended:
```
@@ -26,10 +26,15 @@ class Hierarchy {
   getDescendants(node) {
     if (!this.descendantMap.hasOwnProperty(node)) {
       let descendants = [];
-      for (let child of this.childMap[node]) {
-        descendants.push(child);
-        for (let descendant of this.getDescendants(child)) {
-          descendants.push(descendant);
+
+      // if the given node exists in the "global" child map, build a list of
+      // descendant codes.
+      if (node in this.childMap) {
+        for (let child of this.childMap[node]) {
+          descendants.push(child);
+          for (let descendant of this.getDescendants(child)) {
+            descendants.push(descendant);
+          }
         }
       }
 ```
Specifically I'm wrapping the looping of values from `this.childMap[node]` in a conditional to check if the node exists in there.  I think that means `node` is a leaf node at that point?

What I'm still confused about, is how we've not seen that on other pages.  Are we not dealing with leaf nodes there?

@inglesp – what do you think?

**Comment by inglesp** [comment]
Steps to reproduce:

* Start a new codelist
* Search for "ketoacidosis", and:
  * include:
    * 56051008 (Ketoacidosis)
  * exclude:
    * 55571001 (Alcoholic ketoacidosis)
    * 420422005 (Ketoacidosis in diabetes mellitus)
    * 111556005 (Diabetic ketoacidosis without coma)
* Search for "ketoacidosis in diabetes mellitus"
* On the page for "ketoacidosis in diabetes mellitus" (ie search/ketoacidosis-in-diabetes-mellitus/)
  * un-exclude 111556005 (Diabetic ketoacidosis without coma)

**Comment by inglesp** [comment]
The bug occurs when un-including or un-excluding a concept on a page for search term, where that concept has an ancestor which is included or excluded, but does not match the current search term, and where that ancestor has a descendant which also does not match the current search term.

Here are simpler (the simplest?) steps to reproduce:

* Start a new codelist
* Search for "bone cyst of shoulder girdle", and:
  * include:
    * 767853006 (Bone cyst of shoulder girdle)
    * 1076991000119107 (Bone cyst of left shoulder)
* Search for "bone cyst of left shoulder"
* On the page for "bone cyst of left shoulder" (ie search/bone-cyst-of-shoulder-girdle/)
  * un-include 1076991000119107 (Bone cyst of left shoulder)

**Comment by inglesp** [comment]
I'm pretty sure the double call to the `setState` updater function is a red herring -- it looks like it gets called twice only when there is an exception in the updater code.  The FF console output is a bit confusing -- you see logs from the body of the function twice, and then you see the exceptions twice, but you'd expect to see them interleaved.
