### ISSUE TITLE
Regenerate SNOMED CT codelists

### ISSUE THREAD

**Issue by inglesp** [opensafely/opencodelists#166]
Now that #117 has been understood, we should:

* merge #163 
* delete and reimport all mapping rows using [`import_data`](https://github.com/opensafely/opencodelists/blob/master/opencodelists/management/commands/import_data.py) management command 
  * the data is at `/mnt/volume-lon1-01/opencodelists-data/data/nhs_datamigration_29.0.0_20200401000001/Mapping Tables/Updated/Clinically Assured/ctv3sctmap2_uk_20200401000001.txt` on smallweb1
* regenerate codelists
  * delete existing codelists (they'll have " (SNOMED)" in the title)
  * recreate with [`convert_codelist`](https://github.com/opensafely/opencodelists/blob/master/codelists/management/commands/convert_codelist.py)

**Comment by ghickman** [comment]
* Mapping rows live in the `ctv3sctmap2_mapping` table.

* Command to regenerate those is `python manage.py import_data mappings.ctv3sctmap2 nhs_datamigration_29.0.0_20200401000001`.  This assumes the `pym import_data mappings.ctv3sctmap2 nhs_datamigration_29.0.0_20200401000001/` directory has the structure mentioned above.

* Codelists can be found and deleted from `python manage.py shell` with:
```
from codelists.models import Codelist

Codelist.objects.filter(name__icontains="snomed").delete()
```

**Comment by ghickman** [comment]
This was done with:

1. backup database: `cp db.sqlite3{,.bak}`.
1. build a list of conversion commands `for c in Codelist.objects.filter(name__icontains="snomed"): print(f"./with_environment.sh ./manage.py convert_codelist opensafely {c.slug}")`.
1. create `convert-codelist.sh` on the server with the output of the previous, a bash shebang, `set -xe`, and remove the `-snomed` suffixes from each slug (with `:%s/-snomed//` in vim).
1. Empty the CTV3 -> SNOMED mapping table: `from mappings.ctv3sctmap2.models import Mapping;Mapping.objects.all().delete()`
1. Reload the mapping table: `./with_environment.sh ./manage.py import_data mappings.ctv3sctmap2 /mnt/volume-lon1-01/opencodelists-data/data/nhs_datamigration_29.0.0_20200401000001`.
1. Test a [single codelist](https://codelists.opensafely.org/codelist/opensafely/diabetes-snomed): `./with_environment.sh ./manage.py convert_codelist opensafely diabetes` (removing from it from `convert-codelist.sh`).
1. Run `./convert-codelist.sh`

---

Manually fixed errors:
* `permanent-immunosuppresion` is a misspelling of `permanent-immunosuppression`
* `temporary-immunosuppresion` is a misspelling of `temporary-immunosuppression`
