### ISSUE TITLE
Single Code Hierarchies

### ISSUE THREAD

**Issue by ghickman** [opensafely/opencodelists#193]
TLDR: they don't currently work, but should they?

When we instantiate a Hierarchy with a single code we get an instance no edges and thus no nodes.  This only appears to affect two tests currently and I can't see a reason to build a single code codelist in normal usage.

Either way we need to fix the affected tests (which will be part of my work on #100), but should we also add a conditional to `Hierarchy.from_codes()` to guard against codes being <2?

**Comment by inglesp** [comment]
Do you have an example?

**Comment by ghickman** [comment]
I hit this with `1067731000000107` via the tests which use `CodelistFactory`.

You can recreate in a terminal with:
```
from codelists.hierarchy import Hierarchy
from coding_systems.snomedct import coding_system

h = Hierarchy.from_codes(coding_system, "1067731000000107")

h.nodes == set()  # True
```

**Comment by inglesp** [comment]
The second argument to `Hierarchy.from_codes` should be a list of codes, not a single code.

**Comment by ghickman** [comment]
Ah, that makes sense.

We should probably guard against the string version then?

**Comment by inglesp** [comment]
Could do -- but where are we calling it with a string?

**Comment by inglesp** [comment]
Ah right.  Strings being iterable is a nice convenience in Python, but it does cause this kind of footgunnery sometimes.  Maybe an `assert not isinstance(codes, str)` at the top of the function?
