### ISSUE TITLE
This field is required removes csv

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/opencodelists#245]
Tiny thing but when you trigger the error `This field is required` it always removes the csv in my experience requiring go through the browse button again to find the file. Not a big deal but I imagine it could be slightly annoying in some instances.

![image](https://user-images.githubusercontent.com/40460354/95319217-80d94400-088f-11eb-90ce-f245d594f65e.png)

**Comment by ghickman** [comment]
Unfortunately this is a browser security measure.  When a form fails validation the app returns the form page to you with the data you submitted pre-filled in, by telling each field "your value is $brians_input", but browsers block this for file fields to make sure a User is always involved with picking files that get uploaded.

**Comment by inglesp** [comment]
How much work would it be to do the validation in JS to prevent the form being submitted at all if anything is invalid?
