### ISSUE TITLE
Why do some but not all DOACs have explicit Snomed contraindication?

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/opencodelists#278]
We have generated a codelists for [explicitly contraindicated DOACs](https://codelists.opensafely.org/codelist/opensafely/explicit-contraindication-to-doacs-direct-acting-anticoagulants/2020-10-19/). Three of the DOACs have explicit allergy and contraindication codes but edoxaban has none. Why is this?

I have checked the [NHS Digital SNOMED browser](https://termbrowser.nhs.uk/?) and it appears that all the explicit contraindications at a chemical level are local UK extensions and none exist for edoxaban. A quick look at ramipril (an unrelated blood pressure med) shows allergy held at the international level of snomed. 

Not very important for our task at hand but I am keen to understand this inconsistency. Some questions

- Why would some but not all DOACs have a local extension for contraindications?
- What is the process for authoring a new code specific to a single chemical? i.e. does the company need to apply like dm+d or is it an internal idea in NHS or should it be handled in the international  version.

**Comment by StuartAbbott** [comment]
Explicit allergy and contraindication codes would only be added if they are requested by someone. As edoxaban hasn't got those, it means no one has requested them. Its possible they've not been requested because no one has needed to record that in a clinical record. 

The company/manufacturer could request the allergy and contraindication codes but I have never known a company to do so. The requests come from clinicians or clinical system suppliers. All requests for clinical codes in the SNOMED CT UK clinical extension must be raised via the NHS Digital Request Submission Portal https://isd.hscic.gov.uk/rsp/

**Comment by brianmackenna** [comment]
Thanks @StuartAbbott that's really helpful and reassuring we haven't missed anything. 

Another colleague at NHS Digital has also provided some further helpful information about allergy recording. 

> there has been a general shift in the recording and sharing of allergies information from using the pre-coordinated clinical concepts of “X allergy” to capturing the information within the information model. 


There are [FIHR standards](https://developer.nhs.uk/apis/digitalmedicines-alpha/build_allergy_lists.html#causative-agents) and PRSB have done work on [edischarge / outptaient letters](https://theprsb.org/standards/outpatientletterstandard/).  The PRSB have a browser here which is quite a [good visual representation](https://theprsb.org/wp-content/uploads/2018/06/General-Hospital-Discharge-Maintenance-Release-v1-230518.html) to help understand it.

![image](https://user-images.githubusercontent.com/40460354/98115672-17088600-1e9f-11eb-8b12-049816c5219a.png)

I'm going to close issue but it has prompted discussion between @inglesp about [Snomed-CT expressions](https://confluence.ihtsdotools.org/display/DOCSTART/7.+SNOMED+CT+Expressions) that we may want to utilise on OpenCodelists at some point. Documenting here for when we get to it.
