### ISSUE TITLE
Think about what a YAML format for codelists (and related functions) would look like

### ISSUE THREAD

**Issue by sebbacon** [opensafely/opencodelists#41]

**Comment by inglesp** [comment]
@sebbacon I'm not sure where this fits in.  Is this part of a study definition?

**Comment by sebbacon** [comment]
Could be. It's simply that we are going to move from Python to a YAML format for study definitions (which could be round-tripped from a UI). 

I would imagine it would be its own file which the study definition references by id or similar, but I don't have a clear idea yet. It should be easy to understand and explain, and be usefully diffable.

**Comment by sebbacon** [comment]
Closing this in favour of a general (TBC) "move from Python to YAML" ticket
