### ISSUE TITLE
Validate CSV structure

### ISSUE THREAD

**Issue by inglesp** [opensafely/opencodelists#48]
In the first instance, we should validate that every row of an uploaded CSV file contains the same number of columns.  If a CSV file fails validation, the user should get a helpful message.

This applies to creating a codelist, creating a version, and updating a version.

**Comment by ghickman** [comment]
Do we know how many columns there should be or are we looking for "rows which don't match the median"?

**Comment by inglesp** [comment]
How about checking that each non-header row has the same number of columns as the header row?
